### ISSUE TITLE
withdraw

### ISSUE THREAD

**Issue by limjy92** [kucoin-community-chain/KIPs#3]
I made a deposit, but can I withdraw it from the exchange?

Withdrawal transaction: https://explorer.kcc.io/en/tx/0xe855970677d8923c611a377d520aefbfd50175dd7242efa186fd0240d707cffd

kucoin-wallet : 0xc7f21fe23638b5ceea6155c973a9a46f178914e3

1,932.64615273 matic

Please withdraw to the exchange. Please restore it.

**Comment by viaweb3** [comment]
The token has been sent to 0x4fd884afb58aefc9a898c264189235fe2668b7e1.
